[package]
name = "generate-bindings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cbindgen = "0.26.0"
rustdoc-json = "0.8.7"
serde_json = "1.0.107"
